### ISSUE TITLE
Make compatible with eyeglass

### ISSUE THREAD

**Issue by strarsis** [jakegiltsoff/sassline#37]
Making this module eyeglass-ready makes it easy and consistent 
to install it from a npm package and import it in sass.

[https://github.com/sass-eyeglass/eyeglass](More information about eyeglass).
eyeglass [yeoman generator](https://github.com/sass-eyeglass/generator-eyeglass) for easily preparing the project.

Thank you and
with best regards

**Comment by jakegiltsoff** [comment]
@strarsis can you give anymore information as to what would be needed here?

**Comment by strarsis** [comment]
https://github.com/jakegiltsoff/sassline/pull/41

Besides eyeglass support, @importing the sassline-base.scss results in lots of quite opinionated styles, is this intended?

With best regards

**Comment by jakegiltsoff** [comment]
@strarsis Thank you for spending time on this, but I don’t feel the benefits of adding this will help many people compared to the additional complexity and maintenance it will require. I’m going to close this and the PR.
