### ISSUE TITLE
bower.json syntax error 2.1.1

### ISSUE THREAD

**Issue by ivelrrat** [jakegiltsoff/sassline#38]
There is a missing comma between ignore and license. it causes this error:

```
bower sassline#~2.1.0         download https://github.com/designbyjake/sassline/archive/2.1.1.tar.gz
bower sassline#~2.1.0          extract archive.tar.gz
bower sassline#~2.1.0       EMALFORMED Failed to read /var/folders/sj/crhhxh_j1hx0qyw1mkrp3p9w0000gp/T/user/bower/2c6683b334210585a2c29a625954d04d-66677-TWbKPa/bower.json
```

**Comment by designbyjake** [comment]
@ivelrrat Thanks for letting me know, fixed.

**Comment by razor-x** [comment]
Can you make a point release tag with this fix: anyone using bower will not be able to use a version newer than 2.0.0 until you do. Thanks.

**Comment by jakegiltsoff** [comment]
> point release tag

@razor-x sorry what does that mean?

**Comment by razor-x** [comment]
Sorry for the confusion. I just mean make a new git tag (release), say `v2.1.2`. Since bower "versions" are just git tags, installing via bower will still fail until there is a newer tag with this fix.

**Comment by TheJaredWilcurt** [comment]
"sassline": "latest",

Still happening. Make a new release.

**Comment by jakegiltsoff** [comment]
Version bumped to fix issue.
